apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ie02mbppi-go
  janus-idp.io/tekton: ie02mbppi-go
  backstage.io/kubernetes-id: ie02mbppi-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ie02mbppi-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
