apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ie02mbppi-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ie02mbppi-go 
  name: ie02mbppi-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ie02mbppi-go 
